name: CD

on:
  push:
    branches: [main]

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_PUBLIC_KEY: ${{ secrets.SUPABASE_PUBLIC_KEY }}
      SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

  deploy:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: despliegue en render
        run: curl -f "${{ secrets.RENDER_DEPLOY_HOOK }}"

# Si en el futuro se quiere activar Railway,comente las lineas de render y descomenta estas líneas y configura los secrets necesarios:
#      - name: Clonar repositorio
#        uses: actions/checkout@v4
#
#      - name: Instalar Railway CLI
#        run: npm install -g @railway/cli
#
#      - name: Deploy a Railway
#        run: railway up --service ${{ secrets.RAILWAY_SERVICE_ID }}
#        env:
#          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          